export const PROFIL_2024 = {
  tahun: 2024,
  bulan: "Desember",
  penduduk: { total: 1610, lakiLaki: 833, perempuan: 777, keluarga: 483 },
  wilayah: {
    luasHa: 743.21,
    lingkungan: 7,
    penggunaan: [
      { nama: "Perkebunan", hektare: 382 },
      { nama: "Persawahan", hektare: 40 },
      { nama: "Permukiman", hektare: 30 },
      { nama: "Kuburan", hektare: 1.5 },
      { nama: "Pekarangan", hektare: 4 },
      { nama: "Taman", hektare: 0.5 },
      { nama: "Perkantoran", hektare: 0.1 },
      { nama: "Prasarana umum lainnya", hektare: 0.5 },
    ],
    hutanProduksiTerbatasHa: 264.61,
  },
  tanamanPangan: [
    { nama: "Padi sawah", hektare: 40 },
    { nama: "Jagung", hektare: 15 },
    { nama: "Kangkung", hektare: 3.5 },
    { nama: "Talas", hektare: 1.5 },
    { nama: "Tomat", hektare: 0.5 },
    { nama: "Mentimun", hektare: 0.5 },
  ],
  pekerjaan: [
    { nama: "Buruh tani", jumlah: 364 },
    { nama: "Petani", jumlah: 280 },
    { nama: "Karyawan perusahaan swasta", jumlah: 66 },
    { nama: "Pegawai negeri sipil", jumlah: 48 },
    { nama: "Pedagang keliling", jumlah: 42 },
    { nama: "Pengusaha kecil dan menengah", jumlah: 15 },
  ],
  fasilitas: {
    puskesmasPembantu: 1,
    posyandu: 1,
    dokterUmum: 1,
    bidan: 1,
    perawat: 1,
    sumurPompa: 18,
    sumurGali: 115,
    mataAir: 7,
    jalanAspalMeter: 2410,
    jalanBetonMeter: 367,
    kios: 13,
    usahaPeternakan: 8,
    usahaPerikanan: 1,
  },
} as const;
