"use client";
import Link from "next/link";
import { Edit3, Plus, Trash2 } from "lucide-react";
import { useState } from "react";
import { ConfirmDialog } from "./confirm-dialog";
import { DataTable, type DataColumn } from "./data-table";
import { GlassButton, GlassChip } from "@/components/shared/glass";
import { glassToast } from "@/components/shared/toast";
import { deleteLayanan } from "@/app/admin/(protected)/layanan/actions";
type Row = { id: string; nama: string; slug: string; ringkasan: string | null; urutan: number; aktif: boolean };
export function ServiceTable({ rows }: { rows: Row[] }) { const [selected, setSelected] = useState<Row | null>(null); const [loading, setLoading] = useState(false); async function remove() { if (!selected) return; setLoading(true); const result = await deleteLayanan(selected.id); setLoading(false); setSelected(null); glassToast(result.error ?? result.success ?? "Selesai."); } const columns: DataColumn<Row>[] = [{ key: "nama", label: "Nama", render: (value, row) => <div><p className="font-bold">{String(value)}</p><p className="text-xs text-muted">/{row.slug}</p></div> }, { key: "ringkasan", label: "Ringkasan" }, { key: "aktif", label: "Status", render: (value) => <GlassChip className={value ? "text-emerald-700" : "text-muted"}>{value ? "Aktif" : "Nonaktif"}</GlassChip> }, { key: "urutan", label: "Urutan" }, { key: "id", label: "Aksi", render: (_, row) => <div className="flex gap-2"><Link href={`/admin/layanan/${row.id}`} className="glass-pill p-2 text-[var(--primary)]" aria-label={`Edit ${row.nama}`}><Edit3 size={16} /></Link><button className="glass-pill p-2 text-red-600" onClick={() => setSelected(row)} aria-label={`Hapus ${row.nama}`}><Trash2 size={16} /></button></div> }]; return <><div className="mb-4 flex justify-end"><Link href="/admin/layanan/tambah"><GlassButton><Plus size={17} />Tambah layanan</GlassButton></Link></div><DataTable columns={columns} rows={rows} empty="Belum ada layanan." /><ConfirmDialog open={Boolean(selected)} onClose={() => setSelected(null)} onConfirm={() => void remove()} loading={loading} title="Hapus layanan?" description={`Layanan ${selected?.nama ?? ""} akan dihapus.`} confirmLabel="Hapus" /></>; }
