"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowDown, ArrowUp, Plus, Save, Trash2 } from "lucide-react";
import { GlassButton } from "@/components/shared/glass";
import { glassToast } from "@/components/shared/toast";
import { saveLayanan } from "@/app/admin/(protected)/layanan/actions";
type Service = { id?: string; nama?: string; slug?: string; ringkasan?: string | null; syarat?: unknown; alur?: unknown; biaya?: string | null; estimasi_waktu?: string | null; urutan?: number; aktif?: boolean };
function asList(value: unknown) { return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : []; }
function toSlug(value: string) { return value.toLowerCase().normalize("NFKD").replace(/[^\w\s-]/g, "").trim().replace(/[\s_]+/g, "-").replace(/-+/g, "-"); }
export function ServiceForm({ initial }: { initial?: Service }) {
  const router = useRouter(); const [slug, setSlug] = useState(initial?.slug ?? ""); const [slugEdited, setSlugEdited] = useState(Boolean(initial?.slug)); const [requirements, setRequirements] = useState(asList(initial?.syarat)); const [steps, setSteps] = useState(asList(initial?.alur)); const [saving, setSaving] = useState(false);
  function update(list: string[], setter: (value: string[]) => void, index: number, value: string) { setter(list.map((item, current) => current === index ? value : item)); }
  function move(list: string[], setter: (value: string[]) => void, index: number, direction: -1 | 1) { const next = index + direction; if (next < 0 || next >= list.length) return; const copy = [...list]; [copy[index], copy[next]] = [copy[next], copy[index]]; setter(copy); }
  async function submit(form: FormData) { setSaving(true); form.set("slug", slug); form.set("syarat", JSON.stringify(requirements)); form.set("alur", JSON.stringify(steps)); form.set("aktif", String(form.get("aktif") === "on")); const result = await saveLayanan(form); setSaving(false); if (result.error) glassToast(result.error); else { glassToast(result.success ?? "Tersimpan."); router.push("/admin/layanan"); router.refresh(); } }
  const listEditor = (title: string, values: string[], setter: (value: string[]) => void) => <div><h2 className="font-extrabold">{title}</h2><div className="mt-3 space-y-2">{values.map((value, index) => <div className="flex gap-2" key={`${title}-${index}`}><input value={value} onChange={(event) => update(values, setter, index, event.target.value)} className="form-input" /><button type="button" className="glass-pill p-2" onClick={() => move(values, setter, index, -1)} aria-label="Naik"><ArrowUp size={16} /></button><button type="button" className="glass-pill p-2" onClick={() => move(values, setter, index, 1)} aria-label="Turun"><ArrowDown size={16} /></button><button type="button" className="glass-pill p-2 text-red-600" onClick={() => setter(values.filter((_, current) => current !== index))} aria-label="Hapus"><Trash2 size={16} /></button></div>)}</div><button type="button" className="mt-3 inline-flex min-h-10 items-center gap-2 text-sm font-bold text-[var(--primary)]" onClick={() => setter([...values, ""])}><Plus size={16} />Tambah item</button></div>;
  return <form action={submit} className="glass-strong space-y-6 rounded-[28px] p-5 sm:p-8"><input type="hidden" name="id" value={initial?.id ?? ""} /><div className="grid gap-5 md:grid-cols-2"><label className="font-bold md:col-span-2">Nama layanan<input required name="nama" defaultValue={initial?.nama ?? ""} onChange={(event) => { if (!slugEdited) setSlug(toSlug(event.target.value)); }} className="form-input" /></label><label className="font-bold">Slug<input required name="slug" value={slug} onChange={(event) => { setSlugEdited(true); setSlug(toSlug(event.target.value)); }} className="form-input" /></label><label className="font-bold">Urutan<input type="number" min="0" name="urutan" defaultValue={initial?.urutan ?? 0} className="form-input" /></label></div><label className="block font-bold">Ringkasan<textarea name="ringkasan" rows={3} defaultValue={initial?.ringkasan ?? ""} className="form-input" /></label><div className="grid gap-6 md:grid-cols-2">{listEditor("Syarat", requirements, setRequirements)}{listEditor("Alur", steps, setSteps)}</div><div className="grid gap-5 sm:grid-cols-2"><label className="font-bold">Biaya<input name="biaya" defaultValue={initial?.biaya ?? ""} className="form-input" /></label><label className="font-bold">Estimasi waktu<input name="estimasi_waktu" defaultValue={initial?.estimasi_waktu ?? ""} className="form-input" /></label></div><label className="flex min-h-11 items-center gap-3 font-bold"><input type="checkbox" name="aktif" defaultChecked={initial?.aktif ?? true} /> Aktif dan tampil untuk warga</label><div className="flex justify-end"><GlassButton type="submit" disabled={saving}>{saving ? "Menyimpan..." : <><Save size={17} />Simpan layanan</>}</GlassButton></div></form>;
}
